// <auto-generated />
using System;
using MegaDeskRazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaDeskRazorPages.Migrations
{
    [DbContext(typeof(MegaDeskRazorPagesContext))]
    [Migration("20201106011338_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaDeskRazorPages.Pages.Models.MegaDesk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName");

                    b.Property<int>("DepthDesk");

                    b.Property<string>("Drawers");

                    b.Property<string>("Material");

                    b.Property<DateTime>("QuoteDate");

                    b.Property<string>("RushDays");

                    b.Property<int>("SizeDesk");

                    b.Property<int>("TotalCost");

                    b.Property<int>("WidthDesk");

                    b.HasKey("ID");

                    b.ToTable("MegaDesk");
                });
#pragma warning restore 612, 618
        }
    }
}
